### ISSUE TITLE
Ability to use other endpoints

### ISSUE THREAD

**Issue by razza12** [klaviyo/node-klaviyo#17]
We are trying to implement Back in stock notification as at [klaviyo](https://help.klaviyo.com/hc/en-us/articles/360006565332-Shopify-Back-in-Stock-for-Developers) - a POST to https://a.klaviyo.com/api/v1/catalog/subscribe

However there is no endpoint for it in this package- and we seem unable to use the public.publicRequest method for it as it requires a POST (where by default these are GETs). Do you have a suggested solution for this?

**Comment by njparadis** [comment]
This endpoint is a bit of an odd duck - it uses a public API key for authentication, but otherwise works like any of the V1 API endpoints. For the time being, we are going to hold off on supporting it in the SDKs.
