### ISSUE TITLE
JSDoc method signature typings

### ISSUE THREAD

**Issue by tbeseda** [klaviyo/node-klaviyo#18]
Hi Klaviyo devs,

I appreciate that types were added to this package! but I think the JSDoc comments here need some updating.

Currently they're defined like this for the `public.track` method:
```js
/**
 * Create an event (metric) in Klaviyo for a profile.
 * https://www.klaviyo.com/docs/http-api#track
 * @param {string} event Event name to be tracked.
 * @param {string} email Email address.
 * @param {string} id External id for customer.
 * @param {object} properties Information about the event.
 * @param {object} customerProperties Information about the customer.
 * @param {number} timestamp Time the event occurred.
 * @param {string} ipAddress Ip address of the customer.
 * @param {boolean} isTest Should this be a test request.
 * @returns {Promise.<number|KlaviyoAPIError>} 1 (pass) or 0 (fail) | Non-200 response received
 */
  track({...
```
But that `@param` notation means my editor (and Typescript) thinks each of those is a name parameter instead of a property of an object. So it wants me to call it like `KlaviyoClient.public.track('MyEvent', 'a.user@foo.bar', 'externalId', { }... etc.)`

There are a few ways to handle this. When I'm using JSDoc I use a `@typedef` block like below. But it gets weird with destructuring method arguments, so I changed some of the actual code here too 😐
```js
/**
 * Track Payload
 * @typedef {object} TrackPayload
 *
 * @property {string} event Event name to be tracked.
 * @property {string} email Email address.
 * @property {string} id External id for customer.
 * @property {object} properties Information about the event.
 * @property {object} customerProperties Information about the customer.
 * @property {number} timestamp Time the event occurred.
 * @property {string} ipAddress Ip address of the customer.
 * @property {boolean} isTest Should this be a test request.
 */

/**
 * Create an event (metric) in Klaviyo for a profile.
 * https://www.klaviyo.com/docs/http-api#track
 * @param {TrackPayload} payload
 * @returns {Promise.<number|KlaviyoAPIError>} 1 (pass) or 0 (fail) | Non-200 response received
 */
track(payload) {
  const {
    event,
    email,
    id,
    properties={},
    customerProperties={},
    timestamp,
    ipAddress,
    isTest=false
  } = payload;
  ...
```

There are probably other, more terse ways that may not require changes to actual code.

It's not urgent or a huge deal, just an inconvenience with strict typing environments.

Cheers.

**Comment by Ian-Montgomery-Klaviyo** [comment]
There is an actual Typescript SDK in development that will leverage our new APIs. 

Please read our [Migrating from V1/V2 to the new Klaviyo APIs](https://developers.klaviyo.com/en/docs/migrating-from-v1v2-to-the-new-klaviyo-apis) and [Comparison between v1/v2 and new APIs](https://developers.klaviyo.com/en/docs/apis_comparison_chart) to understand the differences between the old and new APis

**Comment by Ian-Montgomery-Klaviyo** [comment]
There is an actual Typescript SDK in development that will leverage our new APIs. 

Please read our [Migrating from V1/V2 to the new Klaviyo APIs](https://developers.klaviyo.com/en/docs/migrating-from-v1v2-to-the-new-klaviyo-apis) and [Comparison between v1/v2 and new APIs](https://developers.klaviyo.com/en/docs/apis_comparison_chart) to understand the differences between the old and new APis
