### ISSUE TITLE
Missing typescript

### ISSUE THREAD

**Issue by KristofferTolboll2** [klaviyo/node-klaviyo#21]
This library has not Typescript support?!

![image](https://user-images.githubusercontent.com/43782552/120083024-55c58e00-c0c6-11eb-8d12-eeaa9eb4b7fd.png)

I can't add `yarn add @types/node-klayviyo` or with npm. 

Can this really be true?

**Comment by shogo54** [comment]
It seems like they do not support Typescript currently. I'm hoping that they start supporting TS soon.

**Comment by conspireagency** [comment]
Agreed!  Might be helpful w/ things like the Identify API that just returns 0 or 1 response 😅

**Comment by cjmyles** [comment]
Any indication from the contributors when this will be available? It's difficult building projects without Typescript interfaces these days. Ideally the library would be refactored rather than adding a separate `@types/node-klayviyo` library.

**Comment by Ian-Montgomery-Klaviyo** [comment]
A typescript library is in progress and will be available soon. It will be leveraging the new Klaviyo API.

Read our [Migrating from V1/V2 to the new Klaviyo APIs](https://developers.klaviyo.com/en/docs/migrating-from-v1v2-to-the-new-klaviyo-apis) and [Comparison between v1/v2 and new APIs](https://developers.klaviyo.com/en/docs/apis_comparison_chart) for some additional context.

**Comment by Ian-Montgomery-Klaviyo** [comment]
The typescript version is now in open beta check it out [here](https://github.com/klaviyo/klaviyo-api-node/tree/typescript-beta)
