### ISSUE TITLE
Inconsistency and error with "time" parameter

### ISSUE THREAD

**Issue by BodiePaden** [klaviyo/node-klaviyo#24]
For the track method, a "timestamp" parameter is required, but the API is expecting "time".  The code properly maps it in the track event as "time: timestamp", but in the track-once event, it's still "timestamp: timestamp".

The whole notion of "timestamp" should go away as it's never used in the API anywhere.  It's always called "time" and that's what one would expect to pass in to the event.  But also I don't think the time is working at all on track-once as is since it's passing "timestamp" when the API is expecting "time".

I found this because I was passing in "time" for tracking Order Placed events and loading historical data, but realized my "time" parameter was being ignored.  I changed it to "timestamp" and it works now for my purposes.

The fix should probably include some backward compatibility now to accept either time or timestamp, but in either case, pass the "time" parameter to the API in the end.

**Comment by jordanallain** [comment]
`trackOnce` passes the "timestamp" to `track`

https://github.com/klaviyo/node-klaviyo/blob/master/lib/public.js#L153

as you mentioned, `track` maps it to "time"

https://github.com/klaviyo/node-klaviyo/blob/master/lib/public.js#L114

as long as you are passing in "timestamp", either method should use it correctly.

**Comment by BodiePaden** [comment]
Yup, agreed that "timestamp" works.  I guess I was just expecting some consistency that if I see the Klaviyo API documentation expecting "time" that I would use the same term with the library.  If that type of consistency isn't important, then updating the examples as you've done is probably good enough to prevent someone else from getting stuck the same way I did.

**Comment by jordanallain** [comment]
That is understandable, thank you for the feedback. Part of our hope with the SDK is that developers won't need to reference the API documentation. Including the "timestamp" in the README example should hopefully mitigate any future confusion. I think by using that name for the kwarg it is a bit clearer what format the data should be in.
