### ISSUE TITLE
Get profile from email address

### ISSUE THREAD

**Issue by brendonlamb** [klaviyo/node-klaviyo#26]
Is this not possible with this package (I don't see it documented)? - Could it be?

Per this thread 
https://community.klaviyo.com/apis-40/how-can-i-export-person-id-by-using-their-email-address-602

Maybe `getProfile` could handle IDs - AND - email addresses?

`KlaviyoClient.profiles.getProfile('cool@beans.com');`

or

`KlaviyoClient.profiles.getProfileFromEmail('cool@beans.com');`

TY! Awesome package all the same!

**Comment by brendonlamb** [comment]
Additionally, if `KlaviyoClient.public.identify()` would simply return a Klaviyo profile ID - we could store it from the inception. 

FWIW - `KlaviyoClient.lists.addMembersToList()` does this (returns a profile ID)

**Comment by njparadis** [comment]
This endpoint is supported in version 1.1.0 and up!
https://github.com/klaviyo/node-klaviyo/blob/master/CHANGELOG.md#110---2021-04-01

It's available on the `profiles` object:
https://github.com/klaviyo/node-klaviyo/blob/master/lib/profiles.js#L93-L98

I will get some examples added to the README in a future PR

**Comment by brendonlamb** [comment]
Awesome! Thanks you!
