### ISSUE TITLE
track events don't get tracked - missing properties in documentation

### ISSUE THREAD

**Issue by leonardlin** [klaviyo/node-klaviyo#30]
Following the documentation I tried to track an event, but nothing showed up in Klaviyo UI.

// Track a user's behavior - create an event in Klaviyo
KlaviyoClient.public.track({
    event: 'Ordered Pizza',
    email: 'pizza.dave@mailinator.com',
    properties: {
        items: [
            {
                size: 'Large',
                toppings: [
                    'Pepperoni',
                    'Onions',
                    'Smoked Gouda'
                ],
                price: 23.99
            }
        ],
        $value: 23.99
    },
    customerProperties: {
        likesOnions: true
    },
    timestamp: 1532806824
});

Merging it with the documentation about API here:
https://help.klaviyo.com/hc/en-us/articles/360038562411-Setting-Up-API-based-Website-Activity-Events#server-side-requests2

I had to modify the event call for the event to work:
* add customer_properties.$email
* fix field-name customerProperties -> customer_properties
* fix field-name timestamp -> time

// adjusted version that works
KlaviyoClient.public.track({
    event: 'Ordered Pizza',
    email: 'pizza.dave@mailinator.com',
    customer_properties: {
      $email: 'pizza.dave@mailinator.com',
    }.
    properties: {
        items: [
            {
                size: 'Large',
                toppings: [
                    'Pepperoni',
                    'Onions',
                    'Smoked Gouda'
                ],
                price: 23.99
            }
        ],
        $value: 23.99
    },
    time: 1532806824
});

**Comment by njparadis** [comment]
Tested this on the latest release (1.1.3) and was unable to reproduce:
![image](https://user-images.githubusercontent.com/30503294/133096551-940d8e3d-d7ce-4a5c-a264-5449bd28b11f.png)
