### ISSUE TITLE
Tracking "Active on Site" event with node-klaviyo

### ISSUE THREAD

**Issue by brendonlamb** [klaviyo/node-klaviyo#31]
So I can't seem to find any documentation regarding this. There's just this discussion:
https://community.klaviyo.com/apis-40/track-user-active-on-site-event-from-server-side-1047

We have an SPA using React... The standard client-side JS "Active on Site" event hasn't been reliable, it seems to fire at page load... I assume navigation changes aren't considered activity/automatically tracked?

Also FWIW, our GA reports ~1500 active users, while our Klaviyo reports ~300

Anyway in an effort to move all even tracking to our server, I've tried this:

```
const { email } = user.profile;
const event = "__activity__"; // I've also tried "Active on Site" which creates a wholly new metric in Klaviyo
const properties = {
  page: "https://www.example.com/",
  browser: "Server", // to be tracked properly
  os: "Server", // to be tracked properly
  $use_ip: true,
  $is_session_activity: true
};
const customer_properties = {
  $email: email,
  $last_referrer: {
    ts: new Date(),
    value: "",
    first_page: "https://www.google.com/" // to be tracked properly
  }
};
const klaviyoResponse = await KlaviyoClient.public.track({ event, email, properties, customer_properties });
```

Which does reply with a `1` but _doesn't_ appear on the user profile activity feed.

How can we track "Active on Site" explicitly or should we just create a custom event that fires on every page view with `$is_session_activity:true`

Thanks!

**Comment by njparadis** [comment]
Hey @brendonlamb! Currently Klaviyo will aggregate individual page views from a single session into one "Active on Site" event. If you need more granular session data, a custom "Active on Site" metric, similar to what you've described, is one viable solution.

The standard web tracking doesn't play very well with SPAs - the only reliable way to ensure it recognizes a page load/state change is to re-render `klaviyo.js`.
