### ISSUE TITLE
Update SDK before breaking infrastructure change....

### ISSUE THREAD

**Issue by nojacko** [klaviyo/node-klaviyo#32]
Just been told by support 

> API requests to URLs larger than 32kb will be rejected by our new infrastructure starting on August 10, 2021.
> 
> ...if you are using Python, Node.js, Ruby & PHP SDKs to make /track calls rather than forming calls manually, these SDKs will all be updated in the next 7 day

_Edited: Removed my annoyance. Thanks dev team._

**Comment by njparadis** [comment]
No problem @nojacko! I've followed up with our support team to review your ticket - it looks like an out of date macro wasn't removed from rotation after the SDKs were updated.
