### ISSUE TITLE
KlaviyoApiError: Request failed with status code: 414

### ISSUE THREAD

**Issue by leonardlin** [klaviyo/node-klaviyo#34]
I'm using the node-klaviyo 1.1.3

It runs well but every few days it crashes with an error message:
KlaviyoApiError: Request failed with status code: 414

It happens asynchroniously.
I have a try - catch around all klaviyo.track calls, but it happens later and it crashes my node process.

The stacktrace of the error
![image](https://user-images.githubusercontent.com/5815009/140417190-f4ab1c2d-2356-4fbd-b3e8-d0f1989594d2.png)

Any idea why I get 414: uri too long?

It happens on small or large payloads.
It also happens on identify() and track()

The follow-up question is also, how can I catch such an error that it doesn't tear down my whole node process.

**Comment by njparadis** [comment]
Hey @leonardlin! This is related to an infrastructure update we made earlier this year (mentioned in #32). The solution here is to use the post option for track/identify:
```javascript
// Track a user's behavior - create an event in Klaviyo
KlaviyoClient.public.track({
    event: 'Ordered Pizza',
    email: 'pizza.dave@mailinator.com',
    post: true,
});
```

**Comment by leonardlin** [comment]
Thanks I try to use post.
however my identify() call already uses post and it happend there too.
