### ISSUE TITLE
Migrate to ES Modules

### ISSUE THREAD

**Issue by davidhousedev** [klaviyo/node-klaviyo#36]
Currently, this package imports dependencies via `require`. This prevents this package from being used in environments like Vercel Edge Functions, which execute in a V8 runtime and only support ESM.

I was hoping to use this package to simplify frontend personalization based on Klaviyo profile properties, but will need to roll my own API client in order to meet my runtime environment constraints. If there was an ESM-native version of this package, I could use it without a problem.

To read more: https://vercel.com/docs/concepts/functions/edge-functions#runtime

Thanks!

**Comment by Ian-Montgomery-Klaviyo** [comment]
Take a look at our new Node SDK, it allows for ES style imports and could be what your looking for. https://github.com/klaviyo/klaviyo-node-sdk

**Comment by Ian-Montgomery-Klaviyo** [comment]
There is now a newer SDK that uses the new (and improved) Klaviyo API [here](https://github.com/klaviyo/klaviyo-api-node) 

If you need help migrating, please follow the instructions below and read our [Migrating from V1/V2 to the new Klaviyo APIs](https://developers.klaviyo.com/en/docs/migrating-from-v1v2-to-the-new-klaviyo-apis) and [Comparison between v1/v2 and new APIs](https://developers.klaviyo.com/en/docs/apis_comparison_chart).
