### ISSUE TITLE
Tracking: Ability to use a profileId as a user identifier when tracking

### ISSUE THREAD

**Issue by mufudzimasaire** [klaviyo/node-klaviyo#40]
It seems that the ability to use a `profileId`  for tracking web behaviour via a custom server-side implementation is currently not possible - ie. looking at the [track API](https://a.klaviyo.com/api/track).

We are resorting to using a user's email address as an identifier, which works. However,  the problem arises when using the param `utm_email` - suggested in the [testing docs](https://help.klaviyo.com/hc/en-us/articles/115005076767-Guide-to-Klaviyo-Web-Tracking#test-onsite-tracking4).  The issue is due to `email` not being a dynamic variable that can be set under current UTM tracking settings in the admin UI (see below), which means it has to be manually appended to all links. This is not feasible when dealing with multiple marketing campaigns at any given time.

![159667136-bf3ac248-b5f5-40f2-bee6-c3a225735b46](https://user-images.githubusercontent.com/4486874/190150742-b5c0855c-140b-46d7-b860-043372dad2b1.png)

As such, is it possible to extend the [track API](https://a.klaviyo.com/api/track) to accept either an `email` or `profileId` as an identifier? Alternatively, updating the UTM tracking settings to support email as a dynamic variable would resolve the issue?

**Comment by jon-batscha** [comment]
Hey Mufudzi,

Thanks for reaching out! 

I believe we no longer support/recommend including emails in UTM tracking, as emails are technically PII. And you are 100% correct that our legacy API not accepting profile IDs makes this straightforward use-case not possible. 

On the plus side: we just released our new API (still in Beta), which supports creating events using either profile ids, or identifiers (such as email/phone_number/push_token), and so solves for this use case. 

You can find the new endpoint (which replaces track) [here](https://developers.klaviyo.com/en/v2022-09-07.pre/reference/create_event).

Please note: The new API is still in Closed Beta, so you will need to request access [here](https://manage.kmail-lists.com/subscriptions/subscribe?a=9BX3wh&g=VSyTC6). Additionally, there may be some breaking changes so long as it is in Beta. For that reason, we recommend using the Beta API for testing purposes, and caution against using it for production workloads until it is moved to General Availability in a month or so.

We really appreciate this type of feedback, so please don't be shy in reaching out to us with any further issues you run up against.

Cheers,
Jon

**Comment by mufudzimasaire** [comment]
Hey Jon,

Thats great news. We will look into getting access on the new API.

Thanks for the update - much appreciated!

Mufudzi
