### ISSUE TITLE
Expose rate limit data

### ISSUE THREAD

**Issue by freshlogic** [klaviyo/node-klaviyo#6]
The Klaviyo docs (https://help.klaviyo.com/hc/en-us/articles/360038289052-Using-Data-in-Klaviyo#apis5) state "Klaviyo's Track API, for example, has a soft limit of 2,000 requests per second - since our rate-limits are elastic, we do not publish a hard-limit. For our REST APIs we provide in API responses a timestamp for when the next request will be accepted to make it easy to efficiently retry if you do hit a limit."

The rate limits around the list API (https://www.klaviyo.com/docs/api/v2/lists) seems to be significantly lower than 2,000 requests per second. In our testing it's closer to 100 per minute. This was initially surprising to us when doing our onboarding of Klaviyo as we fumbled around looking for rouge code making more than thousands of requests per second.

It's not clear from any docs I've seen _how_ the APIs provide "a timestamp for when the next request will be accepted". Potential options could be the `Retry-After` HTTP header as documented in the HTTP spec: https://tools.ietf.org/html/rfc7231#section-7.1.3. Or the timestamp could be provided in the common `RateLimit-Reset` header that many other popular APIs use: https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html#rfc.section.3.3. In any case, this library does not appear to surface the timestamp.

In the case of code like the following:
```
KlaviyoClient.lists.addSubscribersToList().then(response => {
   // do something with response
}).catch(err => {
   // do something with error
})
```

I'd expect `err` to pass along the timestamp. Like `err.retryAfter`.

Instead, with `err` we get:
- err.message: `Request failed with status code: 429`
- err.statusCode: `429`
- err.data: `Buffer`

If we convert the `err.data` buffer to a string we get a value that looks like JSON: `{"detail":"Request was throttled. Expected available in 35.0 seconds."}`

In our code we could convert the buffer to a string, parse the JSON value, and further parse the detail string with a regular expression to identify the amount of time we should wait before we retry. This approach seems highly volatile. It would simply take a change in the returned error messaging to break our integration.

**Comment by remstone7** [comment]
Thanks for the feedback @freshlogic - we will work on tightening up the response to contain this information!
